name: 'build'


on: ['push', 'pull_request']
jobs:
  source-build:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Use nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Build ui
        run: |
          cd ui
          npm install
          npm run build
          mkdir -p ../api/assets
          cp dist/ui/* ../api/assets

      - name: Build api
        run: |
          cd api
          npm install
          npm run build
          npx pkg . -o rackpilot

      - name: Copy release to remote
        uses: burnett01/rsync-deployments@6.0.0
        with:
          switches: -av
          path: ./
          remote_path: ${{ secrets.RSYNC_PATH }}
          remote_host: ${{ secrets.RSYNC_HOST }}
          remote_user: ${{ secrets.RSYNC_USER }}
          remote_key: ${{ secrets.RSYNC_KEY }}
          remote_key_pass: ${{ secrets.RSYNC_PASS }}